# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-03-12 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='age',
        ),
    ]
